W.en={
cap:"CAPTURE",
capt:"CAPTURE PHOTO",
shoot:"Press [OK] or [5] to shoot",
wait:"WAIT",
proc:"PROCESSING",
procp:"PROCESSING PHOTO...",
pwait:"Please wait",
rev:"REVIEW PHOTO",
send:"SEND",
"del":"DEL",
pg:"PHOTO {1} OF {2}",
add:"ADD MORE",
sendn:"SEND NOW",
delp:"DELETE",
sending:"SENDING",
conf:"CONFIRMATION",
ok:"SENT SUCCESSFULLY!",
back:"The line will call you back.",
newp:"Press [OK] for New Photo",
nw:"NEW",
nonet:"NO INTERNET",
nolink:"The link cannot open.",
opening:"Opening the Haqdaar app...",
sms:"Haqdaar: send your photo here: {link} No internet? Open the Haqdaar app."
};
